using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace R3p.bdo
{
	public enum InteractionType
	{
		InteractionType_GamePlay = 0,
		 InteractionType_ShowCharacterInfo = 1,
		 InteractionType_ExchangeItem = 2,
		 InteractionType_InvitedParty = 3,
		 InteractionType_Talk = 4,
		 InteractionType_Ride = 5,
		 InteractionType_Control = 6,
		 InteractionType_Looting = 7,
		 InteractionType_Collect = 8,
		 InteractionType_OpenDoor = 9,
		 InteractionType_GuildWarehouse = 10,
		 InteractionType_RebuildTent = 11,
		 InteractionType_InstallationMode = 12,
		 InteractionType_ShowHouseInfo = 13,
		 InteractionType_Havest = 14,
		 InteractionType_ParkingHorse = 15,
		 InteractionType_EquipInstallation = 16,
		 InteractionType_UnequipInstallation = 17,
		 InteractionType_InventoryOpen = 18,
		 InteractionType_ShowServantInformation = 19,
		 InteractionType_HouseBussiness = 20,
		 InteractionType_GuildInvite = 21,
		 InteractionType_GuildAllianceInvite = 22,
		 InteractionType_UseItem = 23,
		 InteractionType_UnbuildPersonalTent = 24,
		 InteractionType_Manufacture = 25,
		 InteractionType_Greet = 26,
		 InteractionType_Steal = 27,
		 InteractionType_Lottery = 28,
		 InteractionType_SeedHavest = 29,
		 InteractionType_InstallationPresent = 30,
		 InteractionType_RankerHouseList = 31,
		 InteractionType_HavestLop = 32,
		 InteractionType_HavestKillBug = 33,
		 InteractionType_UninstallTrap = 34,
		 InteractionType_Sympathetic = 35,
		 InteractionType_Observer = 36,
		 InteractionType_HarvestInformation = 37,
		 InteractionType_ClanInvite = 38,
		 InteractionType_OpenSiegeGate = 39,
		 InteractionType_UnbuildKingOrLordTent = 40,
		 InteractionType_Eavesdrop = 41,
		 InteractionType_WaitComment = 42,
		 InteractionType_TakedownCannon = 43,
		 InteractionType_OpenWindow = 44,
		 InteractionType_ChangeLook = 45,
		 InteractionType_ChangeName = 46,
		 InteractionType_RepairKingOrLordTent = 47,
		 InteractionType_UserIntroduction = 48,
		 InteractionType_FollowActor = 49,
		 InteractionType_Upgrade = 50,
		 InteractionType_PvPBattle = 51,
		 InteractionType_SiegeObjectStart = 52,
		 InteractionType_SiegeObjectFinish = 53,
		 InteractionType_GateOpen = 54,
		 InteractionType_GateClose = 55,
		 InteractionType_UninstallBarricade = 56,
		 InteractionType_ServantRepair = 57,
		 InteractionType_LanternOn = 58,
		 InteractionType_LanternOff = 59,
		 InteractionType_Escape = 60,
		 InteractionType_Count = 61,
	}
}