using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace R3p.bdo
{
	public enum PA_UI_CONTROL_TYPE
	{
		PA_UI_CONTROL_PANEL = 0,
		 PA_UI_CONTROL_STATIC = 1,
		 PA_UI_CONTROL_STATICTEXT = 2,
		 PA_UI_CONTROL_BUTTON = 3,
		 PA_UI_CONTROL_CHECKBUTTON = 4,
		 PA_UI_CONTROL_EDIT = 5,
		 PA_UI_CONTROL_RADIOBUTTON = 6,
		 PA_UI_CONTROL_SLIDER = 7,
		 PA_UI_CONTROL_PROGRESS = 8,
		 PA_UI_CONTROL_PROGRESS2 = 9,
		 PA_UI_CONTROL_CIRCULAR_PROGRESS = 10,
		 PA_UI_CONTROL_COMBOBOX = 11,
		 PA_UI_CONTROL_LIST = 12,
		 PA_UI_CONTROL_SCROLL = 13,
		 PA_UI_CONTROL_CHAT = 14,
		 PA_UI_CONTROL_SCROLLWND = 15,
		 PA_UI_CONTROL_SCROLLWND2 = 16,
		 PA_UI_CONTROL_POPUP = 17,
		 PA_UI_CONTROL_TREE = 18,
		 PA_UI_CONTROL_FRAME = 19,
		 PA_UI_CONTROL_FRAME_CONTENT = 20,
		 PA_UI_CONTROL_NUMSTATIC = 21,
		 PA_UI_CONTROL_SLIDESTATIC = 22,
		 PA_UI_CONTROL_GROUPLIST = 23,
		 PA_UI_CONTROL_MOVIECLIP = 24,
		 PA_UI_CONTROL_WEBCONTROL = 25,
		 PA_UI_CONTROL_MULTILINETEXT = 26,
		 PA_UI_CONTROL_MULTILINEEDIT = 27,
		 PA_UI_CONTROL_LIST2 = 28,
		 PA_UI_CONTROL_LIST2_CONTENT = 29,
	}
}